import {
  Award,
  BarChart3,
  BookOpen,
  Bookmark,
  Calendar,
  CreditCard,
  FileText,
  FolderTree,
  GraduationCap,
  Heart,
  History,
  LayoutDashboard,
  LifeBuoy,
  MessageSquare,
  PlusCircle,
  ScrollText,
  Settings,
  Tag,
  TrendingUp,
  User,
  Users,
  Wallet,
} from "lucide-react";

export const NAV_ICONS: Record<string, typeof LayoutDashboard> = {
  // Student
  "/etudiant": LayoutDashboard,
  "/etudiant/formations": BookOpen,
  "/etudiant/certificats": Award,
  "/etudiant/paiements": CreditCard,
  "/etudiant/favoris": Heart,
  "/etudiant/notifications": MessageSquare,
  "/etudiant/calendrier": Calendar,
  "/etudiant/historique": History,
  "/etudiant/profil": User,
  "/etudiant/parametres": Settings,
  "/etudiant/support": LifeBuoy,
  // Trainer
  "/formateur": LayoutDashboard,
  "/formateur/formations": BookOpen,
  "/formateur/formations/creer": PlusCircle,
  "/formateur/etudiants": GraduationCap,
  "/formateur/certificats": Award,
  "/formateur/questions": MessageSquare,
  "/formateur/statistiques": BarChart3,
  "/formateur/revenus": Wallet,
  "/formateur/tarifs": Tag,
  "/formateur/profil": User,
  "/formateur/parametres": Settings,
  // Admin
  "/admin": LayoutDashboard,
  "/admin/utilisateurs": Users,
  "/admin/etudiants": GraduationCap,
  "/admin/formateurs": Users,
  "/admin/categories": FolderTree,
  "/admin/formations": BookOpen,
  "/admin/certificats": Award,
  "/admin/paiements": CreditCard,
  "/admin/coupons": Tag,
  "/admin/statistiques": TrendingUp,
  "/admin/rapports": FileText,
  "/admin/journal": ScrollText,
  "/admin/parametres": Settings,
};
